# Form implementation generated from reading ui file 'SegundaInterfaz.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QDialog, QInputDialog, QLineEdit, QMessageBox,QTableWidgetItem

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(577, 391)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.horizontalLayout.addWidget(self.tableWidget)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButtonUp = QtWidgets.QPushButton(Form)
        self.pushButtonUp.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/prefijoNuevo/FlechaArriba.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonUp.setIcon(icon)
        self.pushButtonUp.setObjectName("pushButtonUp")
        self.verticalLayout.addWidget(self.pushButtonUp)
        self.pushButtonDown = QtWidgets.QPushButton(Form)
        self.pushButtonDown.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/prefijoNuevo/FlechaAbajo.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonDown.setIcon(icon1)
        self.pushButtonDown.setObjectName("pushButtonDown")
        self.verticalLayout.addWidget(self.pushButtonDown)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.pushButtonAdd = QtWidgets.QPushButton(Form)
        self.pushButtonAdd.setObjectName("pushButtonAdd")
        self.pushButtonAdd.clicked.connect(PruebaTabla2.add_item)

        self.verticalLayout.addWidget(self.pushButtonAdd)
        self.pushButtonEdit = QtWidgets.QPushButton(Form)
        self.pushButtonEdit.setObjectName("pushButtonEdit")
        self.verticalLayout.addWidget(self.pushButtonEdit)
        self.pushButtonDelete = QtWidgets.QPushButton(Form)
        self.pushButtonDelete.setObjectName("pushButtonDelete")
        self.verticalLayout.addWidget(self.pushButtonDelete)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        def add_item(self):

            contador = self.tableWidget.rowCount() - 1
            title = "Campo1"
            campo1, ok = QInputDialog.getText(self, title, title)
            if ok and campo1 is not None:
                self.tableWidget.setItem(contador, 0, QTableWidgetItem(campo1))
            title = "Campo2"
            campo2, ok = QInputDialog.getText(self, title, title)
            if ok and campo2 is not None:
                self.tableWidget.setItem(contador, 1, QTableWidgetItem(campo2))
            title = "Campo3"
            campo3, ok = QInputDialog.getText(self, title, title)
            if ok and campo3 is not None:
                self.tableWidget.setItem(contador, 2, QTableWidgetItem(campo3))
            title = "Campo4"
            campo4, ok = QInputDialog.getText(self, title, title)
            if ok and campo4 is not None:
                self.tableWidget.setItem(contador, 3, QTableWidgetItem(campo4))
            self.tableWidget.insertRow(contador + 1)

        def edit_item(self):
            row = self.tableWidget.currentRow()
            col = self.tableWidget.currentColumn()
            item = self.tableWidget.item(row, col)

            if item is not None:
                title = "Edit Item"
                data, ok = QInputDialog.getText(self, title, title, QLineEdit.EchoMode.Normal, item.text())
                if ok and data is not None and data != "":
                    self.tableWidget.setItem(row, col, QTableWidgetItem(data))
                else:
                    QMessageBox.warning(self, "Warning", "El valor no es valido")
            else:
                title = "Edit Item"
                data, ok = QInputDialog.getText(self, title, title, QLineEdit.EchoMode.Normal, "")
                if ok and data is not None and data != "":
                    self.tableWidget.setItem(row, col, QTableWidgetItem(data))
                else:
                    QMessageBox.warning(self, "Warning", "El valor no es valido")

        def remove_row(self):
            row = self.tableWidget.currentRow()

            reply = QMessageBox.question(self, "Borrar Fila", "¿Quieres borrar la fila .form ?",
                                         QMessageBox.StandardButton.Yes | QMessageBox.StandardButton.No)

            if reply == QMessageBox.StandardButton.Yes:
                self.tableWidget.removeRow(row)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Form", "1"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Nº Capa"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Seg Columna"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Cuarta Columna"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Nueva columna"))
        self.pushButtonAdd.setText(_translate("Form", "Añadir"))
        self.pushButtonEdit.setText(_translate("Form", "Editar"))
        self.pushButtonDelete.setText(_translate("Form", "Borrar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
